openapi: 3.0.1
info:
  title: Thumbnails Api v1
  version: v1
servers:
- url: https://thumbnails.roblox.com/
paths:
  /v1/asset-thumbnail-animated:
    get:
      parameters:
      - description: The asset id.
        in: query
        name: assetId
        required: true
        schema:
          format: int64
          type: integer
      - description: (optional) placeid
        in: header
        name: Roblox-Place-Id
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Roblox.Web.Responses.Thumbnails.ThumbnailResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/Roblox.Web.Responses.Thumbnails.ThumbnailResponse'
          description: OK
        "400":
          content: {}
          description: "4: The requested Ids are invalid, of an invalid type or missing."
      summary: Thumbnails asset animated.
      tags:
      - Assets
  /v1/assets:
    get:
      parameters:
      - description: The asset ids.
        explode: false
        in: query
        name: assetIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: (optional) placeid
        in: header
        name: Roblox-Place-Id
        schema:
          format: int64
          type: integer
      - description: Optional policy to use in selecting thumbnail to return (default
          = PlaceHolder).
        in: query
        name: returnPolicy
        schema:
          default: PlaceHolder
          enum:
          - PlaceHolder
          - AutoGenerated
          - ForceAutoGenerated
          type: string
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 30x30
          enum:
          - 30x30
          - 42x42
          - 50x50
          - 60x62
          - 75x75
          - 110x110
          - 140x140
          - 150x150
          - 160x100
          - 160x600
          - 250x250
          - 256x144
          - 300x250
          - 304x166
          - 384x216
          - 396x216
          - 420x420
          - 480x270
          - 512x512
          - 576x324
          - 700x700
          - 728x90
          - 768x432
          - 1200x80
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          - Jpeg
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            8: The requested return policy is invalid (must be PlaceHolder, AutoGenerated\
            \ or ForceAutoGenerated).\r\n10: Circular thumbnail requests are not allowed"
        "403":
          content: {}
          description: "9: User not authorized to use AutoGenerated or ForceAutoGenerated\
            \ return policies."
      summary: Thumbnails assets.
      tags:
      - Assets
  /v1/assets-thumbnail-3d:
    get:
      parameters:
      - description: The asset id.
        in: query
        name: assetId
        required: true
        schema:
          format: int64
          type: integer
      - description: (optional) placeid
        in: header
        name: Roblox-Place-Id
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Roblox.Web.Responses.Thumbnails.ThumbnailResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/Roblox.Web.Responses.Thumbnails.ThumbnailResponse'
          description: OK
        "400":
          content: {}
          description: "4: The requested Ids are invalid, of an invalid type or missing."
      summary: Thumbnails assets.
      tags:
      - Assets
  /v1/badges/icons:
    get:
      parameters:
      - description: The badge ids.
        explode: false
        in: query
        name: badgeIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 150x150
          enum:
          - 150x150
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            10: Circular thumbnail requests are not allowed"
      summary: Thumbnails badge icons.
      tags:
      - Badges
  /v1/bundles/thumbnails:
    get:
      parameters:
      - description: CSV for the bundle ids to get bundle thumbnails
        explode: false
        in: query
        name: bundleIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 150x150
          enum:
          - 150x150
          - 420x420
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            10: Circular thumbnail requests are not allowed"
      summary: Get bundle thumbnails for the given CSV of bundle ids
      tags:
      - Bundles
  /v1/developer-products/icons:
    get:
      parameters:
      - description: The developer product ids.
        explode: false
        in: query
        name: developerProductIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 150x150
          enum:
          - 150x150
          - 420x420
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            10: Circular thumbnail requests are not allowed"
      summary: Thumbnails developer product icons.
      tags:
      - DeveloperProducts
  /v1/game-passes:
    get:
      parameters:
      - description: The game pass ids.
        explode: false
        in: query
        name: gamePassIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 150x150
          enum:
          - 150x150
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            10: Circular thumbnail requests are not allowed"
      summary: Thumbnails game pass icons.
      tags:
      - GamePasses
  /v1/games/{universeId}/thumbnails:
    get:
      parameters:
      - in: path
        name: universeId
        required: true
        schema:
          format: int64
          type: integer
      - explode: false
        in: query
        name: thumbnailIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 768x432
          enum:
          - 768x432
          - 576x324
          - 480x270
          - 384x216
          - 256x144
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          - Jpeg
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            10: Circular thumbnail requests are not allowed"
        "404":
          content: {}
          description: "5: The requested universe does not exist."
      summary: Fetches game thumbnail URLs for a list of universes' thumbnail ids.
        Ids that do not correspond to a valid thumbnail will be filtered out.
      tags:
      - Games
  /v1/games/icons:
    get:
      parameters:
      - description: The universe ids.
        explode: false
        in: query
        name: universeIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: Optional policy to use in selecting game icon to return (default
          = PlaceHolder).
        in: query
        name: returnPolicy
        schema:
          default: PlaceHolder
          enum:
          - PlaceHolder
          - AutoGenerated
          - ForceAutoGenerated
          type: string
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 50x50
          enum:
          - 50x50
          - 128x128
          - 150x150
          - 256x256
          - 420x420
          - 512x512
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          - Jpeg
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            8: The requested return policy is invalid (must be PlaceHolder, AutoGenerated\
            \ or ForceAutoGenerated).\r\n10: Circular thumbnail requests are not allowed"
        "403":
          content: {}
          description: "9: User not authorized to use AutoGenerated or ForceAutoGenerated\
            \ return policies."
      summary: Fetches game icon URLs for a list of universes' root places. Ids that
        do not correspond to a valid universe will be filtered out.
      tags:
      - Games
  /v1/games/multiget/thumbnails:
    get:
      parameters:
      - description: comma-delimited list of universe IDs
        explode: false
        in: query
        name: universeIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: max number of thumbnails to return per universe
        in: query
        name: countPerUniverse
        schema:
          default: 1
          format: int32
          type: integer
      - description: true if defaults (if any) should be returned if no media exists
        in: query
        name: defaults
        schema:
          default: true
          type: boolean
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 768x432
          enum:
          - 768x432
          - 576x324
          - 480x270
          - 384x216
          - 256x144
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          - Jpeg
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Thumbnails.Api.Models.UniverseThumbnailsResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Thumbnails.Api.Models.UniverseThumbnailsResponse]"
          description: OK
        "400":
          content: {}
          description: "0: Unknown error\r\n1: There are too many requested Ids.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            5: The requested universe does not exist.\r\n10: Circular thumbnail requests\
            \ are not allowed"
      summary: Fetch game thumbnail URLs for a list of universe IDs.
      tags:
      - Games
  /v1/groups/icons:
    get:
      parameters:
      - explode: false
        in: query
        name: groupIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 150x150
          enum:
          - 150x150
          - 420x420
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            10: Circular thumbnail requests are not allowed"
      summary: Fetches thumbnail URLs for a list of groups. Ids that do not correspond
        to groups will be filtered out.
      tags:
      - GroupEmblem
  /v1/places/gameicons:
    get:
      parameters:
      - description: The place ids.
        explode: false
        in: query
        name: placeIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: Optional policy to use in selecting game icon to return (default
          = PlaceHolder).
        in: query
        name: returnPolicy
        schema:
          default: PlaceHolder
          enum:
          - PlaceHolder
          - AutoGenerated
          - ForceAutoGenerated
          type: string
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 50x50
          enum:
          - 50x50
          - 128x128
          - 150x150
          - 256x256
          - 420x420
          - 512x512
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          - Jpeg
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            8: The requested return policy is invalid (must be PlaceHolder, AutoGenerated\
            \ or ForceAutoGenerated).\r\n10: Circular thumbnail requests are not allowed"
        "403":
          content: {}
          description: "9: User not authorized to use AutoGenerated or ForceAutoGenerated\
            \ return policies."
      summary: Fetches game icon URLs for a list of places. Ids that do not correspond
        to a valid place will be filtered out.
      tags:
      - Places
  /v1/users/avatar:
    get:
      parameters:
      - description: CSV for the userIds to get avatar full body shots
        explode: false
        in: query
        name: userIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 30x30
          enum:
          - 30x30
          - 48x48
          - 60x60
          - 75x75
          - 100x100
          - 110x110
          - 140x140
          - 150x150
          - 150x200
          - 180x180
          - 250x250
          - 352x352
          - 420x420
          - 720x720
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          - Jpeg
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            10: Circular thumbnail requests are not allowed"
      summary: Get Avatar Full body shots for the given CSV of userIds
      tags:
      - Avatar
  /v1/users/avatar-3d:
    get:
      parameters:
      - description: user Id for avatar
        in: query
        name: userId
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Roblox.Web.Responses.Thumbnails.ThumbnailResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/Roblox.Web.Responses.Thumbnails.ThumbnailResponse'
          description: OK
        "400":
          content: {}
          description: "4: The requested Ids are invalid, of an invalid type or missing."
      summary: Get Avatar 3d object for a user
      tags:
      - Avatar
  /v1/users/avatar-bust:
    get:
      parameters:
      - description: CSV for the userIds to get avatar headshots
        explode: false
        in: query
        name: userIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 48x48
          enum:
          - 48x48
          - 50x50
          - 60x60
          - 75x75
          - 100x100
          - 150x150
          - 180x180
          - 352x352
          - 420x420
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            10: Circular thumbnail requests are not allowed"
      summary: Get Avatar Busts for the given CSV of userIds
      tags:
      - Avatar
  /v1/users/avatar-headshot:
    get:
      parameters:
      - description: CSV for the userIds to get avatar headshots
        explode: false
        in: query
        name: userIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 48x48
          enum:
          - 48x48
          - 50x50
          - 60x60
          - 75x75
          - 100x100
          - 110x110
          - 150x150
          - 180x180
          - 352x352
          - 420x420
          - 720x720
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          - Jpeg
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            10: Circular thumbnail requests are not allowed"
      summary: Get Avatar Headshots for the given CSV of userIds
      tags:
      - Avatar
  /v1/users/outfit-3d:
    get:
      parameters:
      - description: CSV for the userIds to get user outfits
        in: query
        name: outfitId
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Roblox.Web.Responses.Thumbnails.ThumbnailResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/Roblox.Web.Responses.Thumbnails.ThumbnailResponse'
          description: OK
      summary: Get 3d object for an outfit
      tags:
      - Outfits
  /v1/users/outfits:
    get:
      parameters:
      - description: CSV for the userOutfitIds to get user outfits
        explode: false
        in: query
        name: userOutfitIds
        required: true
        schema:
          items:
            format: int64
            type: integer
          type: array
        style: form
      - description: "The thumbnail size, formatted widthxheight"
        in: query
        name: size
        schema:
          default: 150x150
          enum:
          - 150x150
          - 420x420
          type: string
      - description: The thumbnail format
        in: query
        name: format
        schema:
          default: Png
          enum:
          - Png
          type: string
      - description: "The circle thumbnail output parameter, true or false"
        in: query
        name: isCircular
        schema:
          default: false
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            10: Circular thumbnail requests are not allowed"
      summary: Get outfits for the given CSV of userOutfitIds
      tags:
      - Outfits
  /v1/batch:
    post:
      parameters:
      - description: (optional) placeid
        in: header
        name: Roblox-Place-Id
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/Roblox.Thumbnails.Apis.Models.ThumbnailBatchRequest'
              type: array
          text/json:
            schema:
              items:
                $ref: '#/components/schemas/Roblox.Thumbnails.Apis.Models.ThumbnailBatchRequest'
              type: array
        description: "List of ThumbnailBatchRequest objects, may contain the following\
          \ request types:\r\n            1. Avatar\r\n            2. AvatarHeadShot\r\
          \n            3. GameIcon\r\n            4. BadgeIcon\r\n            5.\
          \ GameThumbnail\r\n            6. GamePass\r\n            7. Asset\r\n \
          \           8. BundleThumbnail\r\n            9. Outfit\r\n            10.\
          \ GroupIcon\r\n            11. DeveloperProduct\r\n            12. AutoGeneratedAsset\r\
          \n            13. AvatarBust\r\n            14. PlaceIcon\r\n          \
          \  15. AutoGeneratedGameIcon\r\n            16. ForceAutoGeneratedGameIcon\r\
          \n            17. Look"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailBatchResponse]"
            text/json:
              schema:
                $ref: "#/components/schemas/Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailBatchResponse]"
          description: OK
        "400":
          content: {}
          description: "1: There are too many requested Ids.\r\n2: The requested image\
            \ format is invalid. Please see documentation for valid thumbnail format\
            \ parameter name and values.\r\n3: The requested size is invalid. Please\
            \ see documentation for valid thumbnail size parameter name and format.\r\
            \n4: The requested Ids are invalid, of an invalid type or missing.\r\n\
            7: The specified type is not supported by the batch endpoint"
        "403":
          content: {}
          description: "9: User not authorized to use AutoGenerated or ForceAutoGenerated\
            \ return policies."
      summary: Returns a list of thumbnails with varying types and sizes
      tags:
      - Batch
      x-codegen-request-body-name: requests
components:
  schemas:
    Roblox.Thumbnails.Api.Models.UniverseThumbnailsResponse:
      description: A response model for thumbnails which belong to a specific universe
        ID
      example:
        universeId: 0
        error:
          code: 6
          userFacingMessage: userFacingMessage
          field: field
          fieldData: "{}"
          message: message
        thumbnails:
        - targetId: 0
          imageUrl: imageUrl
          state: Error
          version: version
        - targetId: 0
          imageUrl: imageUrl
          state: Error
          version: version
      properties:
        universeId:
          description: Integer universe ID
          format: int64
          type: integer
        error:
          $ref: '#/components/schemas/Roblox.Web.WebAPI.Models.ApiErrorModel'
        thumbnails:
          description: An array of ThumbnailResponse objects
          items:
            $ref: '#/components/schemas/Roblox.Web.Responses.Thumbnails.ThumbnailResponse'
          type: array
      type: object
    Roblox.Thumbnails.Apis.Models.ThumbnailBatchRequest:
      properties:
        requestId:
          description: "The request id. (Generated client side, used to represent\
            \ the items in the request)"
          type: string
        targetId:
          description: The thumbnail target id
          format: int64
          type: integer
        token:
          description: Alternative ase token used to identify a thumbnail
          type: string
        alias:
          description: "Alternative string used to identify a thumbnail\r\ninstead\
            \ of targetId"
          type: string
        type:
          description: "The type of the thumbnails ['Avatar' = 1, 'AvatarHeadShot'\
            \ = 2, 'GameIcon' = 3, 'BadgeIcon' = 4, 'GameThumbnail' = 5, 'GamePass'\
            \ = 6, 'Asset' = 7, 'BundleThumbnail' = 8, 'Outfit' = 9, 'GroupIcon' =\
            \ 10, 'DeveloperProduct' = 11, 'AvatarBust' = 12, 'AutoGeneratedAsset'\
            \ = 13, 'PlaceIcon' = 14, 'AutoGeneratedGameIcon' = 15, 'ForceAutoGeneratedGameIcon'\
            \ = 16, 'Look' = 17]"
          enum:
          - Avatar
          - AvatarHeadShot
          - GameIcon
          - BadgeIcon
          - GameThumbnail
          - GamePass
          - Asset
          - BundleThumbnail
          - Outfit
          - GroupIcon
          - DeveloperProduct
          - AvatarBust
          - AutoGeneratedAsset
          - PlaceIcon
          - AutoGeneratedGameIcon
          - ForceAutoGeneratedGameIcon
          - Look
          type: string
        size:
          description: The thumbnail size
          type: string
        format:
          description: The thumbnail format
          type: string
        isCircular:
          description: Is the thumbnail circular shape
          type: boolean
      type: object
    Roblox.Thumbs.ImageParameters:
      properties:
        Width:
          format: int32
          type: integer
        Height:
          format: int32
          type: integer
        Format:
          type: string
        IsCircular:
          type: boolean
        FileExtension:
          readOnly: true
          type: string
        MimeType:
          readOnly: true
          type: string
      type: object
    Roblox.Web.Responses.Thumbnails.ThumbnailBatchResponse:
      example:
        targetId: 6
        requestId: requestId
        imageUrl: imageUrl
        errorMessage: errorMessage
        errorCode: 0
        state: Error
        version: version
      properties:
        requestId:
          type: string
        errorCode:
          format: int32
          type: integer
        errorMessage:
          type: string
        targetId:
          format: int64
          type: integer
        state:
          description: " ['Error' = 0, 'Completed' = 1, 'InReview' = 2, 'Pending'\
            \ = 3, 'Blocked' = 4, 'TemporarilyUnavailable' = 5]"
          enum:
          - Error
          - Completed
          - InReview
          - Pending
          - Blocked
          - TemporarilyUnavailable
          type: string
        imageUrl:
          type: string
        version:
          type: string
      type: object
    Roblox.Web.Responses.Thumbnails.ThumbnailResponse:
      example:
        targetId: 0
        imageUrl: imageUrl
        state: Error
        version: version
      properties:
        targetId:
          format: int64
          type: integer
        state:
          description: " ['Error' = 0, 'Completed' = 1, 'InReview' = 2, 'Pending'\
            \ = 3, 'Blocked' = 4, 'TemporarilyUnavailable' = 5]"
          enum:
          - Error
          - Completed
          - InReview
          - Pending
          - Blocked
          - TemporarilyUnavailable
          type: string
        imageUrl:
          type: string
        version:
          type: string
      type: object
    Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Thumbnails.Api.Models.UniverseThumbnailsResponse]:
      example:
        data:
        - universeId: 0
          error:
            code: 6
            userFacingMessage: userFacingMessage
            field: field
            fieldData: "{}"
            message: message
          thumbnails:
          - targetId: 0
            imageUrl: imageUrl
            state: Error
            version: version
          - targetId: 0
            imageUrl: imageUrl
            state: Error
            version: version
        - universeId: 0
          error:
            code: 6
            userFacingMessage: userFacingMessage
            field: field
            fieldData: "{}"
            message: message
          thumbnails:
          - targetId: 0
            imageUrl: imageUrl
            state: Error
            version: version
          - targetId: 0
            imageUrl: imageUrl
            state: Error
            version: version
      properties:
        data:
          items:
            $ref: '#/components/schemas/Roblox.Thumbnails.Api.Models.UniverseThumbnailsResponse'
          type: array
      type: object
    Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailBatchResponse]:
      example:
        data:
        - targetId: 6
          requestId: requestId
          imageUrl: imageUrl
          errorMessage: errorMessage
          errorCode: 0
          state: Error
          version: version
        - targetId: 6
          requestId: requestId
          imageUrl: imageUrl
          errorMessage: errorMessage
          errorCode: 0
          state: Error
          version: version
      properties:
        data:
          items:
            $ref: '#/components/schemas/Roblox.Web.Responses.Thumbnails.ThumbnailBatchResponse'
          type: array
      type: object
    Roblox.Web.WebAPI.Models.ApiArrayResponse[Roblox.Web.Responses.Thumbnails.ThumbnailResponse]:
      example:
        data:
        - targetId: 0
          imageUrl: imageUrl
          state: Error
          version: version
        - targetId: 0
          imageUrl: imageUrl
          state: Error
          version: version
      properties:
        data:
          items:
            $ref: '#/components/schemas/Roblox.Web.Responses.Thumbnails.ThumbnailResponse'
          type: array
      type: object
    Roblox.Web.WebAPI.Models.ApiErrorModel:
      example:
        code: 6
        userFacingMessage: userFacingMessage
        field: field
        fieldData: "{}"
        message: message
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        userFacingMessage:
          type: string
        field:
          type: string
        fieldData:
          type: object
      type: object
x-original-swagger-version: "2.0"

